carrito/urls.py
from django.urls import path
from . import views
app_name = 'carrito'

urlpatterns = [
    path('', views.carrito_detalle, name='carrito_detalle'),
    path('add/<int:producto_id>/', views.agregar_carrito, name='agregar_carrito'),
    path('remover/<int:producto_id>/', views.remover_carrito, name='remover_carrito'),
]

nucleo/urls.py
#creamos un archivo url por cada app para tener una mejor organizacion
#de la bilioteca x importamos la clase path
from django.urls import path
from . import views

app_name = 'nucleo'

urlpatterns = [
    path('', views.index, name='index'), #el nombre puede ser cualquiera
]

ordenes/urls.py
from django.urls import path
from . import views

app_name = 'ordenes'

urlpatterns = [ #lista de urls
    path('crear/', views.crear_orden, name='crear_orden'), 
]

primernegocio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nucleo.urls', namespace='nucleo')),#agregando urls de la app nucleo
    path('tienda/', include('tienda.urls', namespace='tienda')),#agregando urls de la app tienda
    path('carrito/', include('carrito.urls', namespace='carrito')),#agregando carrito de compra
    path('ordenes/', include('ordenes.urls', namespace='ordenes')),#agregando órdenes de compra
    path('accounts/', include('allauth.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                    document_root = settings.MEDIA_ROOT)
                    

tienda/urls.py
#creamos un archivo url por cada app para tener una mejor organizacion
#de la bilioteca x importamos la clase path
from django.urls import path
from . import views

app_name = 'tienda'

urlpatterns = [
#    path('', views.tienda_index, name='tienda_index'), #el nombre puede ser cualquiera
    path('', views.lista_productos, name='lista_productos'),
    path('<slug:categoria_slug>/', views.lista_productos,
        name='lista_productos_por_categoria'),
    path('<int:id>/<slug:slug>/', views.producto_detalle,
        name='producto_detalle'),
]

carrito/models.py
from django.db import models

# Create your models here.

carrito/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from tienda.models import Producto
from .carrito import Carrito
from .formulario import FormularioAgregarProducto

@require_POST   #Esto es un decorador
def agregar_carrito(request, producto_id):
    carrito = Carrito(request)
    producto = get_object_or_404(Producto, id=producto_id)
    formulario = FormularioAgregarProducto(request.POST)
    if formulario.is_valid():
        cd = formulario.cleaned_data
        carrito.add(producto=producto, cantidad=cd['cantidad'],
                    cambiar_cantidad=cd['sobreescribir'])
    return redirect('carrito:carrito_detalle')

@require_POST
def remover_carrito(request, producto_id):
    carrito = Carrito(request)
    producto = get_object_or_404(Producto, id=producto_id)
    carrito.remover(producto)
    return redirect('carrito:carrito_detalle')

def carrito_detalle(request):
    carrito = Carrito(request)
    for item in carrito:
        item['form_actual_cantidad'] = FormularioAgregarProducto(initial={
            'cantidad': item['cantidad'],
            'sobreescribir':  True
        })
    return render(request, 'carrito/detalle.html', {'carrito': carrito})

# Create your views here.

carrito/templates/carrito/detalle.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid">
 <h3>Tu carrito de compra</h3>
 <table class="cart">
  <thead>
   <tr>
    <th>Imagen</th>
    <th>Producto</th>
    <th>Cantidad</th>
    <th>Quitar</th>
    <th>Precio unitario</th>
    <th>Precio</th>
   </tr>
  </thead>

  <tbody>
   {% for item in carrito %}
    {% with producto=item.producto %}
     <tr>
      <td>
       <a href="{{ producto.get_absolute_url }}">
        <img src="{% if producto.imagen %}{{ producto.imagen.url}} 
        {% else %}{% static "img/no_image.png" %}{% endif %}">
       </a>
      </td>
      <td>{{ producto.nombre }}</td>
      <td>{{ item.cantidad }}</td>
      <td>
         <form action="{% url "carrito:agregar_carrito" producto.id %}" method="post">
         {{ item.form_actual_cantidad.cantidad }}
         {{ item.form_actual_cantidad.sobreescribir }}
         <input type="submit" value="Actualizar">
         {% csrf_token %}
         </form>
      </td>
      
      <td>
       <form action="{% url "carrito:remover_carrito" producto.id %}" method="post">
        <input type="submit" value="Eliminar">
        {% csrf_token %}
       </form>
      </td>
      <td class="num">S/.{{ item.precio }}</td>
      <td class="num">S/.{{ item.precio_total }}</td>
     </tr>
    {% endwith %}
   {% endfor %}
<tr class="total">
<td>Total</td>
<td colspan="4"></td>
<td class="num">S/.{{ carrito.obtener_precio_total }}</td>
</tr>
</tbody>

</table>
<p class="text-right">
 <a href="{% url "tienda:lista_productos" %}" 
 class="btn btn-secondary">Continua comprando</a>

 <a href="{% url "ordenes:crear_orden"%}" class="btn btn-success"> Procesar compra </a>

</p>
</div>
{% endblock %}