carrito/urls.py
from django.urls import path
from . import views
app_name = 'carrito'

urlpatterns = [
    path('', views.carrito_detalle, name='carrito_detalle'),
    path('add/<int:producto_id>/', views.agregar_carrito, name='agregar_carrito'),
    path('remover/<int:producto_id>/', views.remover_carrito, name='remover_carrito'),
]

nucleo/urls.py
#creamos un archivo url por cada app para tener una mejor organizacion
#de la bilioteca x importamos la clase path
from django.urls import path
from . import views

app_name = 'nucleo'

urlpatterns = [
    path('', views.index, name='index'), #el nombre puede ser cualquiera
]

primernegocio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nucleo.urls', namespace='nucleo')),#agregando urls de la app nucleo
    path('tienda/', include('tienda.urls', namespace='tienda')),#agregando urls de la app tienda
    path('carrito/', include('carrito.urls', namespace='carrito')),#agregando carrito de compra
    path('ordenes/', include('ordenes.urls', namespace='ordenes')),#agregando órdenes de compra
    path('accounts/', include('allauth.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                    document_root = settings.MEDIA_ROOT)
                    

primernegocio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Mi negocio online</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Fuentes -->
    <link href="{% static 'css/fontawesome-free/css/all.css' %}" rel="stylesheet">
    <link href="{% static 'css/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">
    <!-- Estilos personalizados -->
    <link href="{% static 'css/pagina_inicio.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %} " rel="stylesheet ">
    <link rel='shortcut icon' type='image/x-icon' href="{% static 'img/favicon.ico'%}" />
</head>

<body>
    <main>
        <!-- Barra de navegación -->
        <nav class=" navbar navbar-expand-sm bg-light ">
            <div class="container-fluid ">
                <a class="navbar-brand " href="# ">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" 
                    width="30 " height="30 " class="d-inline-block align-top " alt=" "> PNL-ACTUMLOGOS
                </a>
                <ul class="navbar-nav ">
                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Nosotros</a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Productos</a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Servicios</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Contacto</a>
                    </li>
                </ul>
                <form class="form">


                    <div class="cart">
                        {% with total_items=carrito|length%}
                            {% if total_items > 0%}
                            Tu carrito:
                            <a href="{% url "carrito:carrito_detalle"%}">
                            {{ total_items }}
                            producto{{ total_items|pluralize}},
                            S/. {{ carrito.obtener_precio_total }}
                            </a>
                            {% else %}
                                Tu carrito está vacío
                            {% endif %}
                        {% endwith %}
                    </div>


                    <a class="btn btn-primary " href="{% url "account_login" %}">Iniciar Sesión</a>
                </form>
            </div>
        </nav>

        <!-- Contenido de la página-->
        <div id="content">
            {% block content %} 
            {% endblock%}
        </div>
        <!-- Footer -->
        <footer class="footer bg-light ">
            <div class="container-fluid ">
                <div class="row ">
                    <div class="col-lg-6 h-100 text-center text-lg-left my-auto ">
                        <ul class="list-inline mb-2 ">
                            <li class="list-inline-item ">
                                <a href="# ">Nosotros</a>
                            </li>
                            <li class="list-inline-item ">&sdot;</li>
                            <li class="list-inline-item ">
                                <a href="# ">Contacto</a>
                            </li>
                            <li class="list-inline-item ">&sdot;</li>
                            <li class="list-inline-item ">
                                <a href="# ">Términos de uso</a>
                            </li>
                            <li class="list-inline-item ">&sdot;</li>
                            <li class="list-inline-item ">
                                <a href="# ">Política de privacidad</a>
                            </li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0 ">&copy; 
                        PNL-Actumlogos 2021. Todos los derechos reservados.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-right my-auto ">
                        <ul class="list-inline mb-0 ">
                            <li class="list-inline-item mr-3 ">
                                <a href="https://www.facebook.com ">
                                    <i class="fab fa-facebook fa-2x fa-fw "></i>
                                </a>
                            </li>
                            <li class="list-inline-item mr-3 ">
                                <a href="https://twitter.com/ ">
                                    <i class="fab fa-twitter-square fa-2x fa-fw "></i>
                                </a>
                            </li>
                            <li class="list-inline-item ">
                                <a href="https://www.instagram.com ">
                                    <i class="fab fa-instagram fa-2x fa-fw "></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </main>
</body>

</html>